### ISSUE TITLE
GenomeStudio CNV Table Export

### ISSUE THREAD

**Issue by jng2** [WGLab/PennCNV#101]
Hello,

I am currently running the plugin version of PennCNV on GenomeStudio 2.0.  It works great.  I was wondering if there was a way to export the CNV calls that does not require using the genome viewer.  The full dataset that I would like to run PennCNV on is too big for IGV and it crashes.  

Thank you for any help,

Jeffrey

**Comment by kaichop** [comment]
Yes it can be exported and I think it is stored in the actual penncnv
folder (you do not need to visualize them to export, just take the call
file directly in one of the folders).

**Comment by jng2** [comment]
Thank you, after looking for the folder I was able to find the call files!
