### ISSUE TITLE
.hmm file

### ISSUE THREAD

**Issue by DrFakhar** [WGLab/PennCNV#111]
I am working on SNP Chip data of cattle genome. I have made the .pfb file. From where to download the .hall file for my dataset? i am unable to find any download link?

Sorry in advance, if its a childish question.

**Comment by DrFakhar** [comment]
which file should i use for illumina arrays?
https://github.com/WGLab/PennCNV/blob/master/affy/libgw5/agre.hmm
Or
https://github.com/WGLab/PennCNV/blob/master/affy/libgw6/affygw6.hmm 
Or 
anyother?

**Comment by kaichop** [comment]
I asume you are asking about the hmm file (not the pfb). Generally speaking
if you are using an Illumina array, you can just use the hhall.hmm file.
The "affygw6" and "agre" were originally created for Affymetrix arrays.

**Comment by DrFakhar** [comment]
Thank you for your response.

From where i can download the hhall.hmm file. Kindly guide

Thank you in advance
Fakhar

**Comment by kaichop** [comment]
It is part of PennCNV package.

**Comment by DrFakhar** [comment]
Thank you so much.

Now i need your guidance regarding the preparation of gc model file
Bostaurus 1.9 assembly. Can you please share me the link of gc content
file.

**Comment by kaichop** [comment]
No need to use gc model unless your data is of very low quality.

**Comment by DrFakhar** [comment]
That is great.

Thank you so much.
