### ISSUE TITLE
Create hg38 GC model

### ISSUE THREAD

**Issue by BioinfoRDX** [WGLab/PennCNV#116]
Hi, I downloaded hg38 "gc5BaseBw.txt.gz" which says "/gbdb/hg38/bbi/gc5BaseBw/gc5Base.bw", and in my understanding is not the correct file - reading older posts here I see that there is not a hg38 gc5Base.txt.gz.

How can I build one for the hg38?

**Comment by kaichop** [comment]
can you try the files here. 
https://github.com/WGLab/PennCNV/tree/master/gc_file

**Comment by BioinfoRDX** [comment]
thanks!
