### ISSUE TITLE
PennCNV affy (Genome-wide 6.0 array) apt-probeset-genotype command

### ISSUE THREAD

**Issue by jongleur2056** [WGLab/PennCNV#15]
I used the following command,
$ bin/apt-probeset-genotype -c lib/GenomeWideSNP_6.cdf -a birdseed --read-models-birdseed lib/GenomeWideSNP_6.birdseed.models --special-snps lib/GenomeWideSNP_6.specialSNPs --out-dir apt --cel-files CEL/*.CEL

However got the following error message
FATAL ERROR:TsvFile.cpp:2659: This file is a Calvin file. (filename='CEL/1_Aldo_PBL_Lymph.CEL')

**Comment by kaichop** [comment]
APT is a tool developed by affymetrix so please contact them for support.

**Comment by adammaikai** [comment]
@jongleur2056 did you find a solution to this? I've encountered the same error

**Comment by AnimaTardeb** [comment]
Hello,
 for me the solution was to omit --cel-files while i am using only one CEL file
