### ISSUE TITLE
Version 1.0.4 gives the Segmentation fault for khmm.so

### ISSUE THREAD

**Issue by Sabryr** [WGLab/PennCNV#17]
This is the same issue as https://github.com/WGLab/PennCNV/issues/7. (submitting new as it is closed)

Version 1.0.4 gives the Segmentation fault for khmm.so, tried with Perl 5.8.9 and gcc4.9 on CentOS 6.8. No luck (tried few other combinations as well). I am installing this on our cluster to be used by the University researchers and this has wasted a lot of my time.

**Comment by Riptides** [comment]
dealing with the same problem, did you ever find a combination that worked?

**Comment by moshl** [comment]
Hi, Sabryr. Do you solve your problem? I faced with the same problem, Can you give me some suggestions?

**Comment by kaichop** [comment]
Sorry for the delay in responding to the issue. Please install the latest PennCNV 1.0.5 which improved compatibility, and try compilation again. It is best to just install perl 5.14.2 and with gcc4.9 it should work well without problem in CentOS 6 or CentOS 7.
