### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by agelber** [WGLab/PennCNV#18]
Compiling under perl 5.22 gives me this error in from handy.h
`/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/handy.h:113:34: error: ‘bool’ undeclared (first use in this function)`
`/usr/lib/x86_64-linux-gnu/perl/5.22/CORE/handy.h:113:39: error: expected ‘:’ before numeric constant`

I have added
 `#include <stdio.h>`
`#include <stdbool.h>` 
but the same errors persist.

**Comment by kaichop** [comment]
It could be a gcc issue, or the lack of a header file for perl 5.22.
Perhaps it is best that you install a local perl yourself and run penncnv
on this perl.

**Comment by twhitehead** [comment]
Just ran into this myself.  Looks like it is due to [a bug in older versions of swig](https://github.com/swig/swig/commit/4305a3cef9b210541c3b88ab2fd03d787c3bca66#diff-e00eca1bbacd9d243e51f4bf400b3000R63) that cause it to generate code incompatible with newer versions of perl

**Comment by twhitehead** [comment]
Until the swig generated files get regenerated by a newer version of swig, you can work around this by manually removing the lines that the linked to patch would remove.  Before running `make` do

```bash
sed -i -e '/#undef bool/d' khmm_wrap.c
```

**Comment by kaichop** [comment]
Thank you for the insights!

**Comment by twhitehead** [comment]
NP

**Comment by agelber** [comment]
Thanks! I'll give it a try.
