### ISSUE TITLE
Normal/Neutral copy numbers (cn=2)? -Axiom_array(PMRA)

### ISSUE THREAD

**Issue by lalamot** [WGLab/PennCNV#19]
RE: PennCNV-affy  calling - axiom PMRA array data

Kindly,  I just successfully ran PennCNV-1.0.3 "detect_cnv.pl" to call  cnvs.  I do however noticed that the generated copy numbers are either  cn=1,0,or 3  and no 2(neutral/normal). Kindly how or what   flag do I need to invoke in order  get all segments including the neutral/normal ones?  

Thank you

**Comment by kaichop** [comment]
If it is not shown in results, then it is neutral copy number.

**Comment by lalamot** [comment]
Indeed helpful, thank you so much for the prompt response, it validates our assumption.
Thank you
