### ISSUE TITLE
Generate genotyping calls from CEL files

### ISSUE THREAD

**Issue by dauss75** [WGLab/PennCNV#2]
Hello there,

Thanks for the nice tutorial!

I have calvin CEL files that were converted to text files using apt-cel-convert.
Having the text CEL files, I tried to run the command and got an error: 
apt-probeset-genotype -c lib/GenomeWideSNP_6.cdf -a birdseed --read-models-birdseed lib/GenomeWideSNP_6.birdseed.models --special-snps lib/GenomeWideSNP_6.specialSNPs --out-dir apt --cel-files listfile

FATAL ERROR:TsvFile.cpp:2672: This file appears to be binary. (filename='../data/test.cel/1.CEL')

It's clear that the CEL files are not binary.  
It seems the error is from birdseed, but I was wondering whether you have any thoughts on this.

Thanks,
Segun

**Comment by kaichop** [comment]
you can run Linux command "file" to check whether it is binary or text
file. Also delete this file from listfile and see whether other files have
similar issues.

**Comment by dauss75** [comment]
thanks for the quick reply.
I am running with only four CEL files and using the "file" command, I get: 
1.CEL: data

**Comment by kaichop** [comment]
The file may be corrupt, try other CEL files to see if the same thing
occurs for other files. CEL should be a text file.

**Comment by dauss75** [comment]
I figured out the CEL files were generated based on the CytoScanHD_Array platform.  Trying to convert them now.

**Comment by Vaidhy-M** [comment]
> Hello there,
> 
> Thanks for the nice tutorial!
> 
> I have calvin CEL files that were converted to text files using apt-cel-convert.
> Having the text CEL files, I tried to run the command and got an error:
> apt-probeset-genotype -c lib/GenomeWideSNP_6.cdf -a birdseed --read-models-birdseed lib/GenomeWideSNP_6.birdseed.models --special-snps lib/GenomeWideSNP_6.specialSNPs --out-dir apt --cel-files listfile
> 
> FATAL ERROR:TsvFile.cpp:2672: This file appears to be binary. (filename='../data/test.cel/1.CEL')
> 
> It's clear that the CEL files are not binary.
> It seems the error is from birdseed, but I was wondering whether you have any thoughts on this.
> 
> Thanks,
> Segun

I am facing the same issue in Mapping 500K CEL files. Linux File command says the files are in Data format. Could you please explain how to fix this? Should I convert CEL files to a different format? Thanks!

**Comment by kaichop** [comment]
I cannot tell what is the problem, but perhaps you can delete this file
from the listfile and try again. If there is no more error message, then
perhaps this particular CEL is corrupted and treated as binary.
