### ISSUE TITLE
hmm file for  custom designed array--illumina

### ISSUE THREAD

**Issue by lirr-lichen** [WGLab/PennCNV#22]
Hi Dr. Wang,

I want to use PennCNV to call CNV from a custom designed  pig Illumian array ,this array were designed in 2017.
My problem is that in the CNV calling step, I do not HMM file. 
Can I just use the  hhall.hmm for  no human species Illumina custom designed array?  

Best,
Lichen

**Comment by kaichop** [comment]
you can use hhall.hmm for this.

**Comment by lirr-lichen** [comment]
Thank you for answering my question !

**Comment by dtx282000** [comment]
Hi Dr. Wang,

I want to use PennCNV to call CNV from the 90K Axiom buffalo SNP array.
My problem is that in the CNV calling step. Which HMM file is suitable for my CNV calling? 

Best

**Comment by kaichop** [comment]
hhall.hmm can be used for all Illumina arrays. You just need to create a
PFB file using compile_pfb.pl

**Comment by dtx282000** [comment]
Hi Dr. Wang,

The  90K Axiom buffalo SNP array is not the Illumina array, which belong to the Affymetrix array. And the PFB file has been constructed using the compile_pfb.pl. Now, I would like to know if the affygw6.hmm can be used for all Affymetrix arrays. or any other suggestion?

Best

**Comment by kaichop** [comment]
You can try it. Also see an example paper
https://pubmed.ncbi.nlm.nih.gov/27773354/ for analyzing Axiom array on
human.
