### ISSUE TITLE
Missing files in lib folder?

### ISSUE THREAD

**Issue by KristinaKeuper** [WGLab/PennCNV#23]
I try to use PennCNV for SNP array analysis/ CNV detection. But I miss some files, following the documentation.
The documentation says: 
"In PennCNV, the hhall.hg18.pfb, hhall.hmm and hhall.hg18.gcmodel files have been provided in the lib/ folder. "

Also the 3 files for hh550 should be there I guess. But I only find the .hmm files. Did you remove them? And where can I download these files?

**Comment by kaichop** [comment]
You can use hhall.hmm for HMM model. The hh550 array and hg18 genome
coordinate are no longer used today, and you can prepare these files
yourself following instructions in the website.
