### ISSUE TITLE
WF gc model

### ISSUE THREAD

**Issue by m-gall** [WGLab/PennCNV#24]
Dear Dr Wang,

I am working with an Infinium Oncoarray-500k dataset (hg19 reference).
I was considering applying a correction on the waviness factor, as my WF values exceed 0.04.
Do you know if there are gc models available which might be suitable for this array type?

Kind regards,
Mailie

**Comment by kaichop** [comment]
you can use cal_gc_model.pl program yourself to generate a gcmodel file.
