### ISSUE TITLE
"detect_cnv.pl -validate" shows probability instead of state

### ISSUE THREAD

**Issue by heliac2000** [WGLab/PennCNV#26]
$ runexpl --path_detect_cnv=../detect_cnv.pl 5

    ex5.rawcnv:
    chr3:3957986-4054960          numsnp=50     length=96,975      state86.4199950337373,cn=84.4199950337373 father.txt startsnp=rs11716390 endsnp=rs17039742
    chr20:10511631-10583260       numsnp=10     length=71,630      state11.5231778900509,cn=9.5231778900509 father.txt startsnp=rs8114269 endsnp=rs682562

state and cn have strange values... 

    #assign the score for each region (similar to assignConfidence subroutine)
    sub validateRegion {
                           :
      for my $nextstate (1, 2, 3, 5, 6) {   #do not consider LOH
                           :
        push @logprob, [$logprob + log ($prior_prob->[$stateindex]), $nextstate];
                           : 
      }
                           :
      @logprob = sort {$b->[0]<=>$a->[0]} @logprob;
      my $beststate = $logprob[0]->[0];

`$logprob[0]->[0]`(probability) is assgined to `$beststate`,  but a state value(`$logprob[0]->[1]`) should be assigned. 

      my $beststate = $logprob[0]->[1];

I try to rerun, outputs changed as follows.

    chr20:10511631-10583260       numsnp=10     length=71,630      state2,cn=1 father.txt startsnp=rs8114269 endsnp=rs682562
    chr3:3957986-4054960          numsnp=50     length=96,975      state2,cn=1 offspring.txt startsnp=rs11716390 endsnp=rs17039742

**Comment by jeffverboon** [comment]
same issue!

**Comment by kaichop** [comment]
we will review this and revise.

**Comment by fangli0813** [comment]
Thank you. We have fixed it.
