### ISSUE TITLE
compile_pfb.pl not working

### ISSUE THREAD

**Issue by lsheffield** [WGLab/PennCNV#27]
I am trying to compile my own pfb file from my signal files.
Here is the command I'm passing it:
compile_pfb.pl -listfile /gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/signal_file_list_02.txt -output /gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/pfb_files/pop_b_freq.pfb

The list file looks as follows:
/gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/4770-MA-1651_202566700099_R01C01_formatted_02.txt
/gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/4770-MA-1635_202524980055_R06C01_formatted_02.txt
/gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/4770-MA-1659_202566700099_R08C01_formatted_02.txt

The files it is trying to read look as follows:
SNP Name        Chr     Pos     BFreq   LogR
1:100292476     1       100292476       0.0     -1.02807
1:101064936     1       101064936       0.0728731       0.0350392
1:103380393     1       103380393       1.0     0.0676645

The following are the outputs/errors that are produced when I attempt to run the command:
NOTICE: A total of 1686 input signal files is specified in /gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/signal_file_list_02.txt
WARNING: Skipping the file /gpfs/gpfs2/home/lsheffield/AGHI/formatted_reports/4770-MA-0212_201131650106_R08C01_formatted_02.txt that cannot be read by the current program
Use of uninitialized value $baf_index in addition (+) at /gpfs/gpfs2/software/PennCNV-1.0.4/compile_pfb.pl line 99.
NOTICE: The B Allele Freq information is annotated as column 1 in input files
NOTICE: A total of 0 input files will be used for compiling PFB values
Use of uninitialized value $snp in pattern match (m//) at /gpfs/gpfs2/software/PennCNV-1.0.4/compile_pfb.pl line 128.
Use of uninitialized value $snp in hash element at /gpfs/gpfs2/software/PennCNV-1.0.4/compile_pfb.pl line 140.

**Comment by kaichop** [comment]
The error message below basically says that  /gpfs/gpfs2/home/lsheffield/
AGHI/formatted_reports/4770-MA-0212_201131650106_R08C01_formatted_02.txt
 cannot
be read. Did you check whether there are permission issues (for example
just do a simple "head  /gpfs/gpfs2/home/lsheffield/
AGHI/formatted_reports/4770-MA-0212_201131650106_R08C01_formatted_02.txt
 ").

Basically " A total of 0 input files will be used for compiling PFB values "
so your output is empty. It looks like a simple file reading problem. Make
sure there is no unintended white space, tab character or weird characters
in the list file.

**Comment by lsheffield** [comment]
Thank you
