### ISSUE TITLE
the output file generated from runex.pl 1 is empty

### ISSUE THREAD

**Issue by ZKai0801** [WGLab/PennCNV#28]
Hi,

I was trying to run detect_cnv.pl, however, the generated output file was always empty, even when I tried to use the example provided in the guide. 

Hope you can help me with this.

Thanks!

**Comment by kaichop** [comment]
what's the command line and error/warning message in your screen

**Comment by ZKai0801** [comment]
The command I used is perl runex.pl 1. And there is no error/warning message displayed. 

Here is what I got:

kai@kai-S550CB:~/PennCNV-1.0.4/example$ perl runex.pl 1
Exercise 1: individual-based calling and write the output to ex1.rawcnv
	Running command <detect_cnv.pl -test -hmm example.hmm -pfb example.pfb -conf -log ex1.log -out ex1.rawcnv father.txt mother.txt offspring.txt>

******************************************************************************
NOTICE: All program notification/warning messages that appear in STDERR will be also written to log file ex1.log
NOTICE: Reading marker coordinates and population frequency of B allele (PFB) from example.pfb ... Done with 93129 records
NOTICE: Reading LRR and BAF values for from father.txt ... Done with 93129 records in 4 chromosomes
NOTICE: Data from chromosome X will not be used in analysis
NOTICE: Median-adjusting LRR values for all autosome markers from father.txt by 0.0221
NOTICE: Median-adjusting BAF values for all autosome markers from father.txt by 0.0029
NOTICE: quality summary for father.txt: LRR_mean=0.0027 LRR_median=0.0000 LRR_SD=0.1335 BAF_mean=0.5063 BAF_median=0.5000 BAF_SD=0.0390 BAF_DRIFT=0.000037 WF=0.0184 GCWF=0.0136

******************************************************************************

**Comment by kaichop** [comment]
it looks like the program was interrupted for some reason possibly due to
out of memory, or due to other reasons, since there is no error message but
the program did not finish. You can try compile the source code and see if
there is any error message and then try again.

**Comment by ZKai0801** [comment]
Hi Dr. Wang,

So this time I tried to run the example command manually, 
i.e.: detect_cnv.pl -test -hmm ../lib/hh550.hmm -pfb ../lib/hh550.hg18.pfb -conf -log ex1.log -out ex1.rawcnv father.txt mother.txt offspring.txt

It gave me an error message saying segmentation fault (core dumped).

The full error message showing as follow:
NOTICE: All program notification/warning messages that appear in STDERR will be also written to log file ex1.log
NOTICE: Reading marker coordinates and population frequency of B allele (PFB) from example.pfb ... Done with 93129 records
NOTICE: Reading LRR and BAF values for from father.txt ... Done with 93129 records in 4 chromosomes
NOTICE: Data from chromosome X will not be used in analysis
NOTICE: Median-adjusting LRR values for all autosome markers from father.txt by 0.0221
NOTICE: Median-adjusting BAF values for all autosome markers from father.txt by 0.0029
NOTICE: quality summary for father.txt: LRR_mean=0.0027 LRR_median=0.0000 LRR_SD=0.1335 BAF_mean=0.5063 BAF_median=0.5000 BAF_SD=0.0390 BAF_DRIFT=0.000037 WF=0.0184 GCWF=0.0136
segmentation fault (core dumped)


Also, I noticed that few days ago there is a update of the software. After I updated the software and run the example command again, a new error message shown:
Exercise 1: individual-based calling and write the output to ex1.rawcnv
	Running command <detect_cnv.pl -test -hmm example.hmm -pfb example.pfb -conf -log ex1.log -out ex1.rawcnv father.txt mother.txt offspring.txt>

******************************************************************************
Can't exec "detect_cnv.pl": No such file or directory at runex.pl line 81.

******************************************************************************



I would be very appreciated if you can help me with it!

**Comment by kaichop** [comment]
the segmentaion fault is due to compilation issues. Just re-compile the
program and it should work.

The "cannot execute detect_cnv.pl" is likely due to PATH issues that you do
not have the detect_cnv.pl file in the current path. You can simply run the
command yourself:  Running command <detect_cnv.pl -test -hmm example.hmm
-pfb example.pfb -conf -log ex1.log -out ex1.rawcnv father.txt mother.txt
offspring.txt>

**Comment by ZKai0801** [comment]
Hi, 

Sorry to say that it still doesn't work this time... It just didn't generate result and had no error message.

I thought this may have something to do the Ubuntu I'm using, so I changed my system into mint18. However, I'm now experiencing some difficulty with installing old version of perl. I will keep trying on that. At the meantime, would you mind suggest me a system that most likely get pennCNV to run?

Thank you very much!
