### ISSUE TITLE
can not install PennCNV in Ubuntu 18.04.1 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by Victor0122** [WGLab/PennCNV#30]
I try to install PennCNV to ubuntu 18.04. I did the steps and still get the errors message:

PennCNV compilation error: Your system architecture is 'x86_64-linux-gnu-thread-multi', which is not compatible with pre-compiled executables in PennCNV package.
PennCNV compilation error: Please download source code from http://www.openbioinformatics.org/penncnv and compile executable program.

**Comment by kaichop** [comment]
Sorry for the delay in response. Please follow instructions in the "last resort" section in the http://penncnv.openbioinformatics.org/en/latest/user-guide/install/#compilation-from-source page. Make sure that you use the new perl (use `which perl` to confirm) by setting up the PATH environmental variable.
