### ISSUE TITLE
Error: cannot read from HMM file

### ISSUE THREAD

**Issue by argossy** [WGLab/PennCNV#31]
Hi I tried to run PennCNV with the following command line and error message below. The message says cannot find hmm file but I am pretty sure HMM is in my current folder.
my version of software is: PennCNV 1.04 Perl 5.8.7
Thank you

command line:
detect_cnv.pl -test -hmm affygw6.hmm -pfb affy_LAT_cnv_v0.pfb --chrx --gcmodelfile file.gcmodel -conf -log affy_lat_cnv_chrX.log -out affy_lat_rawcnv_chrX.txt --listfile cnv_filelist.txt

the output error is shown below:
NOTICE: All program notification/warning messages that appear in STDERR will be also written to log file affy_lat_cnv_chrX.log
NOTICE: Reading marker coordinates and population frequency of B allele (PFB) from affy_LAT_cnv_v0.pfb ... Done with 816889 records (115 records in chr MT were discarded)
NOTICE: Reading LRR and BAF values for from affy_cnv/261_0261-1_V3_D270_8000000628_F09_LAT.cnv.txt ... Done with 816889 records in 24 chromosomes (115 records are discarded due to lack of PFB information for the markers)
NOTICE: Adjusting LRR by GC model: WF changes from -0.0513 to -0.0291, GCWF changes from -0.0459 to -0.0165
NOTICE: Data from chromosome 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,Y will not be used in analysis
NOTICE: quality summary for affy_cnv/261_0261-1_V3_D270_8000000628_F09_LAT.cnv.txt: LRR_Xmean=0.0174 LRR_Xmedian=0.0325 LRR_XSD=0.4295 BAF_Xhet=0.2941
NOTICE: Sample sex for affy_cnv/261_0261-1_V3_D270_8000000628_F09_LAT.cnv.txt is predicted as 'female' based on BAF heterozygosity rate (this is different from genotype heterozygosity rate!) for chrX (0.294122300450914)
WARNING: Sample from affy_cnv/261_0261-1_V3_D270_8000000628_F09_LAT.cnv.txt does not pass quality control criteria due to its large SD for LRR (0.429494920336252)!
WARNING: Small-sized CNV calls may not be reliable and should be interpreted with caution!
kc.pm module run-time error (use eval{} in Perl to catch the error) ...
Error: cannot read from HMM file at detect_cnv.pl line 850.

**Comment by kaichop** [comment]
are you sure affygw6.hmm file is at the current directly and it is readable
by you?

**Comment by kaichop** [comment]
try use affygw6.hmm, not "./affygw6.hmm" in the command line.

**Comment by argossy** [comment]
I did that before. doesn't change anything

**Comment by kaichop** [comment]
sorry for losing track of this issue until now. I checked the output again more carefully and see that "WARNING: Small-sized CNV calls may not be reliable and should be interpreted with caution!
kc.pm module run-time error (use eval{} in Perl to catch the error) ...
Error: cannot read from HMM file at detect_cnv.pl line 850." So there is a possibility that the error is in the kc.pm module itself, and for whatever reason it is reported as HMM file not found after kc.pm run-time error. I would suggest that you recompile the source code (make sure to update to the latest version of PennCNV first).
