### ISSUE TITLE
Suggestion for running compile_pfb.pl with 8K samples

### ISSUE THREAD

**Issue by npatel22526** [WGLab/PennCNV#37]
Hello Dr. Wang,

I have about 8K intensity files and it takes quite a long for generating PFB files with all 8K samples.
I am planning to try two different approaches to generate PFB files faster

1. Split SNP position files into 100 parts and run in parallel using argument '-snpposfile' 
2. Run with small number (2K or 4K) of intensity files 

Does either of the above will significantly effect results or have any obvious downside that I am not considering ?

Best, 
Nick

**Comment by kaichop** [comment]
You only need to use 1k files, that would be good enough.
-Kai

**Comment by npatel22526** [comment]
Thanks for clarification.
