### ISSUE TITLE
Axiom binary to text CELS

### ISSUE THREAD

**Issue by Vaidhy-M** [WGLab/PennCNV#38]
Hi there, I am having a hard time converting Axiom raw CEL files to text CELs to use it in PennCNV-Affy protocol. APT fails to do the trick as Axiom files are multi-channel. Since some users here appear to have successfully used Axiom data in PennCNV I feel like I am missing something. Please advise. Thank you for your time,

**Comment by kaichop** [comment]
Did you try whether ATP can directly process the axiom binary CEL file?

**Comment by Vaidhy-M** [comment]
apt-probeset-genotype seems to be the next step but that is not working with raw CEL files.

**Comment by Vaidhy-M** [comment]
Update: Turns out Axiom CELs are multi-channel and too complex to be converted to text CELs. Using apt-probeset-genotype with the correct .xml file on raw binary CELs resolved the issue.
