### ISSUE TITLE
different CNVs between two execution

### ISSUE THREAD

**Issue by Taylor95** [WGLab/PennCNV#40]
Hello,
I have executed the detect_cnv.pl script several months ago and got CNVs based on PennCNV-1.0.4. Then now, I added the command -confidence and ran the same samples again based on PennCNV-1.0.5, but got completely different CNVs. Is this because of the version of PennCNV? or I need to set seed like in R?
Thank you in advance!

**Comment by kaichop** [comment]
Results should be identical. There is no random seed in calling. I think
you just need to make sure that the command line itself is consistent.

You could of course just re-run 1.0.4 again and check if the same results
are obtained, to diagnose what was different in the command line.

**Comment by Taylor95** [comment]
OK, I will check carefully and try again. Thank you for answering!

————————

Yaqian Liu
School of Public Health
Nanjing Medical University

On 4/17/2019 20:35，Kai Wang<notifications@github.com><mailto:notifications@github.com> wrote：
Results should be identical. There is no random seed in calling. I think
you just need to make sure that the command line itself is consistent.

You could of course just re-run 1.0.4 again and check if the same results
are obtained, to diagnose what was different in the command line.
