### ISSUE TITLE
custom pfb - duplicate values

### ISSUE THREAD

**Issue by andri90** [WGLab/PennCNV#43]
Hey,

I am trying to create my own pfb for Illumina GSA. I compiled the pfb using 500 samples. The output is quite big and I noticed that there are a lot of duplicates, with different baf values. How should I deal with the duplicates? Do they somehow affect the next step detect_cnv? Can I remove them?

![image](https://user-images.githubusercontent.com/51119653/58474950-dc001000-814c-11e9-95b3-ac34a20fd87b.png)

**Comment by kaichop** [comment]
This should not occur. Are they the exact same SNP? Did you check that
these duplicates are in the original input files (same location, but
different SNP identifiers?)
-Kai

**Comment by andri90** [comment]
I doublechecked my procedure and found out it was due to a problem with splitting the original Illumina report that contained the samples. I now have a pfb file with unique values. Thank you

-Andri

**Comment by kaichop** [comment]
Okay thank you for the update.
