### ISSUE TITLE
Unable to locate HMM File for Axiom UKB Array

### ISSUE THREAD

**Issue by npatel22526** [WGLab/PennCNV#46]
Hello,

I am running PennCNV on about 9K samples and noticed that HMM file is not available for  Axiom UKB Array. 
Would it be possible to use "affygw6.hmm" instead ? or the model file has to be generated by "train". 

Best, 
Nick

**Comment by kaichop** [comment]
sorry that I missed this email. No need to train and you can use the affygw6.hmm. Also check the paper http://www.sciencedirect.com/science/article/pii/S0006322316327111 to see how they used Axiom array.

**Comment by npatel22526** [comment]
Thanks for suggestion. That is the paper I followed and they have trained the model using 100 samples but wanted to checked with you as script says "--train                     train optimized HMM model (**not recommended to use**)"
