### ISSUE TITLE
PennCNV-Affy for Genome-wide 6.0

### ISSUE THREAD

**Issue by Taylor95** [WGLab/PennCNV#49]
Hello,
I am trying to call CNVs from Genome-wide 6.0 array and it has data of 906,600 SNPs and 946,000 CN probes.  I wonder what is the calling based on, SNPs or CN probes? In .rawcnv, startsnp and endsnp contain both SNPs and CN probes. Can PennCNV-Affy package call CNVs just based on CN probes?

And, I found the BAF value of CN probes are all 2 in individual signal file, could this affect the calling CNVs? The following is a example of individual signal file :

> CN_496308	1	836746	0.3908	2
CN_522419	1	818586	-0.1996	2
CN_489691	1	824136	0.3437	2

Thanks in advance!

**Comment by kaichop** [comment]
BAF=2 means that there is no BAF (it is not a SNP marker)

**Comment by Taylor95** [comment]
So, if I want to call CNVs based on CN probes, I just need to remove SNP markers?
How will it deal since both PFB and BAF value are 2?

**Comment by kaichop** [comment]
No, you do not need to do anything. PennCNV can call CNV using both SNP
markers and CN markers.
