### ISSUE TITLE
CNV calling on Illumina Omni 2.5M array

### ISSUE THREAD

**Issue by thomasyu888** [WGLab/PennCNV#5]
Thanks in advance for your time.  I was just confirming if this would be the correct way to use detect_cnv.pl on illumina Omni data:

```
./detect_cnv.pl -test -hmm lib/hh550.hmm -pfb [ generated pfb file from annotation /signal files ] [ signal files] -log ../sample.log -out sampleall.rawcnv 
```
Best,
Tom

**Comment by kaichop** [comment]
It is best to use hhall.hmm, rather than hh550.hmm. Other than that, the
command looks fine.

**Comment by thomasyu888** [comment]
Thank you for your help!
