### ISSUE TITLE
GCmodel not in /lib

### ISSUE THREAD

**Issue by YannLeGuen** [WGLab/PennCNV#51]
Hi,

I would like to run the detect_cnv.pl script and adjust by GCmodel, as in the example 3
```
$ perl runex.pl  3
Exercise 3: individual-based calling with GCmodel signal adjustment, write to ex3.rawcnv
	Running command <detect_cnv.pl -test -hmm example.hmm -pfb example.pfb -log ex3.log -out ex3.rawcnv -gcmodel ../lib/hh550.hg18.gcmodel -conf -list inputlist>
```
In the FAQ http://penncnv.openbioinformatics.org/en/latest/misc/faq/ it is written that

> gcmodel files have been provided in the lib/ folder.

However, this is not the case. Could you clarify where I can find these GCmodel files for Illumina arrays. I found the ones for Affymetrix arrays at:
http://www.openbioinformatics.org/penncnv/download/gw6.tar.gz

Thanks,
Yann

**Comment by kaichop** [comment]
You can build GC model for your array (the file differs for each array) by cal-gc-snp

**Comment by YannLeGuen** [comment]
Thank you for the advice. This was also in the FAQ.
Since I have data from an old Illumina platform, I was your curious to compare it with the one that is apparently required to run the example 3 quoted above.
It's ok if it is not available/distributed anymore.

**Comment by YannLeGuen** [comment]
Hi, 

In this case, do you advise to build a gcmodel for each individual? and then adjust each individual signal with genomic_wave.pl?
cal_gc_snp seems to take as input individual subject signal and not a file list as detect_cnv does..

Thanks

**Comment by kaichop** [comment]
gcmodel is for each array, not for each individual. It includes gc for each
marker in the array. cal_gc_snp uses the input file because it has the
information on the marker (chr, position).

**Comment by YannLeGuen** [comment]
I see thank you.
