### ISSUE TITLE
Run example issue

### ISSUE THREAD

**Issue by gaiusjaugustus** [WGLab/PennCNV#6]
I am trying to get PennCNV working on my linux computing server.  Here's what I've done, per this document: http://penncnv.openbioinformatics.org/en/latest/user-guide/install/

-Downloaded + decompressed
-loaded perl (5.14.2) & R/2.15.2 modules (global modules)
-went to kext folder and used make
-went to penncnv folder and typed "perl ./detect_cnv.pl".  The proper usage information appears
-added to my export PATH = statement in my bashrc file, "$HOME/opt/penncnv" where the files are located

I then navigated to the example folder to try to run those, using this document as a guide: http://penncnv.openbioinformatics.org/en/latest/user-guide/startup/

-Ran "perl runex.pl", got proper usage information
-Ran "perl runex.pl 1", and got Error: "Can't exec detect_cnv.pl: (null) at example/runex.pl line 81"
-Ran "perl runex.pl -path_detect_cnv ../detect_cnv.pl", same error occurs.
-Also tried going up to the main penncnv folder and using "perl example/runex.pl 1 -path_detect_cnv detect_cnv.pl", but get the same error.

Not sure where to start diagnosing the issue here.   I have already contacted support for my server, but haven't heard back yet. I'm hoping this is something I can fix easily.  Thank you in advance for any help.
Gaius

**Comment by kaichop** [comment]
You need to add the path to environmental variable, such that you can
directly run "runex.pl" without "perl". Type "which runex.pl" to make sure
that the PATH is actually working. Then try this again.

**Comment by gaiusjaugustus** [comment]
Thank you for the quick reply.

I have added the example folder to the environmental variable.  "which runex.pl" outputs the folder which it is located.  ("~/opt/penncnv/example/run.pl").  I also verified that "which detect_cnv.pl" outputs the proper folder.

I can now run "runex.pl" without the "perl", however, when I do "runex.pl 1".  Below is the error I receive.

Full error:

PennCNV compilation error: Can't locate loadable object for module khmm in @INC (@INC contains: /home/u5/gaiusjaugustus/opt/penncnv/ /home/u5/gaiusjaugustus/opt/penncnv/kext/5.10.1 /home/u5/gaiusjaugustus/opt/penncnv/kext /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/u5/gaiusjaugustus/opt/penncnv/kext/khmm.pm line 8
Compilation failed in require at /home/u5/gaiusjaugustus/opt/penncnv/detect_cnv.pl line 10.

PennCNV compilation error: Your system architecture is 'x86_64-linux-thread-multi', which is not compatible with pre-compiled executables in PennCNV package.
PennCNV compilation error: Please download source code from http://www.openbioinformatics.org/penncnv and compile executable program.

**Comment by kaichop** [comment]
Just try run detect_cnv.pl itself (or "perl detect-cnv.pl"), and see
whether you can execute it. If not, then there is a problem with
compilation.

runex.pl is just a wrapper that execute detect_cnv.pl. it does print out
the command line that it uses to execute detect_cnv.pl. you can just run
the command line yourself.

**Comment by gaiusjaugustus** [comment]
Okay, doesn't work.  So the issue is with compilation.  I assume this is something to work out with my server folks to fix, correct?  In the meantime, I'll just put it in things in the folder with my files and run it that way.

Thank you.

**Comment by gaiusjaugustus** [comment]
I saw in the documentation that there are some issues with Perl 5.14/5.18.  This is the version I am using.  Is it possible this is the problem?  If so, what version of Perl would you suggest using, so I can install it.  Thank you.

**Comment by kaichop** [comment]
Perl 5.8 or 5.10 would work.
