### ISSUE TITLE
Error: no snpdist defined

### ISSUE THREAD

**Issue by elinejk** [WGLab/PennCNV#69]
Hi,
When I run **detect_cnv.pl -trio** using a custom pfb file for the Illumina GSA array I get the following error: 

> ERROR: For nextregion 22,kgp15099441,rs530422334, pos=rs5030865.1 rs78482768 kgp15099441 rs530422334 22:42529918_CYP2D6 sample1.txt sample2.txt sample3.txt: no snpdist defined!!!

In detect_cnv.pl this is:

> ERROR: for nextregion $nextsubregion, pos=@nextpos @$ref_inputfile: no snpdist defined!!!

Do you have any suggestions on how to solve this?
Thanks!

**Comment by hezht3** [comment]
I also met with this issue. I wonder whether there's any suggestion on resolving this? Thanks.

**Comment by elinejk** [comment]
If I remember correctly, the error is the result of multiple SNPs with the same coordinates. Because they have the same position, PennCNV trio calling is unable to calculate the distance between the SNPs. My solution to this, while not ideal, was to change the input files so that there was only one SNP for each position

**Comment by SamGreen52** [comment]
Hello! Currently receiving this issue, was there any other additional solutions that you may have found?

**Comment by kaichop** [comment]
Try check whether all SNPs have coordinates defined in the PFB file. If
not, make new signal files by including only SNPs that are defined in the
PFB file.
