### ISSUE TITLE
qcnumcnv

### ISSUE THREAD

**Issue by psychrb** [WGLab/PennCNV#70]
For filter.cnv.pl:
1) What is the default for qcnumcnv without inserting a flag..? If this flag is not added, is there any filtering..?
2) This is the maximum number of cnv's/sample for inclusion in filtered output, correct?..
So if qcnumcnv 80 is inserted, a sample with more than 80 will be excluded, correct?

**Comment by kaichop** [comment]
If it is not specified, then the filter is not used.
The number depends on the array, and is typically selected by researchers
themselves based on extreme value that are observed in a specific data set,
to exclude some samples from analysis.
