### ISSUE TITLE
Running PennCNV in parallel

### ISSUE THREAD

**Issue by sophie-03** [WGLab/PennCNV#82]
I am currently calling CNVs from SNP genotype arrays using detect_cnv.pl, I have 500,000 samples so this is taking quite a long time. Is there a way to run this in parallel to speed up the process?

**Comment by kaichop** [comment]
You can run in 500 threads, each with 1000 samples (put file name in a list
file). This can be done rapidly if you are allowed to submit 500 jobs at
the same time in your computing cluster.
