### ISSUE TITLE
FYI: compiler compatibility issue

### ISSUE THREAD

**Issue by ink1** [WGLab/PennCNV#9]
FYI, building under RH7/CentOS7 works fine but results in a build which does not work. The issue seems to be related to the default compiler (gcc 4.8.5). Using the compatibility compiler (gcc44 4.4.7) instead produces a build which works (tested by comparing the results of examples 1,2, 4-6, 13-16 the output for which are provided).

Note that this is using Perl 5.16.3 (default on RH7) and may be related to the so-called "Perl compatibility issue" reported elsewhere.

**Comment by kaichop** [comment]
Thanks for the comments.
