### ISSUE TITLE
Question: Can PennCNV differentiate homozygous and heterozygous CNV calls?

### ISSUE THREAD

**Issue by vikrantsingh1** [WGLab/PennCNV#95]
Hello! Currently we are performing CNV analysis using PennCNV and wondering if can determine that CNV calls are homozygous and heterozygous? i.e., if we have a deletion/duplication on one chromosome only or on both chromosomes?
Many thanks,
Vikrant

**Comment by kaichop** [comment]
homozygous and heterozygous are different states. For deletions, cn=0 means
homozygous, and cn=1 means heterozygous.

**Comment by vikrantsingh1** [comment]
Thank you so much the prompt reply.
