### ISSUE TITLE
Missing files from affymetrix website

### ISSUE THREAD

**Issue by e-sollier** [WGLab/PennCNV#96]
Hello,

I would like to process CEL files from Affymetrix arrays (SNP6.0 and 500k). I tried to follow the tutorial at https://penncnv.openbioinformatics.org/en/latest/user-guide/affy/  but this requires downloading http://www.affymetrix.com/Auth/support/downloads/library_files/genomewidesnp6_libraryfile.zip , which results in an error 404 for me. 

Is it possible to download this data from elsewhere, or is there any other solution ?

Thanks in advance for your help.

**Comment by kaichop** [comment]
The 500K and 6.0 arrays are quite old,  so I would guess the URL has
changed. I would suggest that you explore the Affymetrix website a bit to
see whether there are other places to download library files or even
directly email them to find it.

**Comment by e-sollier** [comment]
Thanks for the suggestion!
I indeed managed to find the Affymetrix library files at https://www.thermofisher.com/de/de/home/life-science/microarray-analysis/microarray-data-analysis/genechip-array-library-files.html. For example the 6.0 data can be downloaded from https://sec-assets.thermofisher.com/TFS-Assets/LSG/Support-Files/genomewidesnp6_libraryfile.zip. 
Perhaps the link in https://penncnv.openbioinformatics.org/en/latest/user-guide/affy/ could be updated, so that other users do not face the same issue.

**Comment by kaichop** [comment]
Thank you. The links are updated.

**Comment by suyanxun** [comment]
> Thanks for the suggestion! I indeed managed to find the Affymetrix library files at https://www.thermofisher.com/de/de/home/life-science/microarray-analysis/microarray-data-analysis/genechip-array-library-files.html. For example the 6.0 data can be downloaded from https://sec-assets.thermofisher.com/TFS-Assets/LSG/Support-Files/genomewidesnp6_libraryfile.zip. Perhaps the link in https://penncnv.openbioinformatics.org/en/latest/user-guide/affy/ could be updated, so that other users do not face the same issue.

I can not get the file from  https://sec-assets.thermofisher.com/TFS-Assets/LSG/Support-Files/genomewidesnp6_libraryfile.zip, could you share it? thanks
