### ISSUE TITLE
Singularity use

### ISSUE THREAD

**Issue by lgmgeo** [WGLab/PennCNV#98]
Hi,

First of all, thanks for PennCNV, it's a great tool!

I would like to use singularity (I'm really not an expert) but my attempts remained unsuccessful

Here are the commands I run:
```
singularity pull penncnv.sif docker://genomicslab/penncnv
singularity exec penncnv.sif detect_cnv.pl -h
```
But I got the following error message:
```
/.singularity.d/actions/exec: line 21: exec: detect_cnv.pl: not found
```

Thank you for any help you can provide me,

Véronique

**Comment by kaichop** [comment]
can you supply the full path  /home/user/PennCNV/detect_cnv.pl in the
command.

**Comment by lgmgeo** [comment]
Thank you for your help ;o)

To resume all the install steps:
```
cd /home/user/
git clone https://github.com/WGLab/PennCNV.git
singularity pull penncnv.sif docker://genomicslab/penncnv
```
To run:
```
singularity exec penncnv.sif /home/user/PennCNV/detect_cnv.pl -h
```
Is it correct?

**Comment by kaichop** [comment]
Try it, I do not know and have no experience, but supplying full path
solves the 'exec not found' problem.
You can also invoke an interactive shell and then run penncnv commands
within the shell.

**Comment by lgmgeo** [comment]
Thank you very much, the help command is working. 
I will run PennCNV on our data.
